[build]
  publish = "dist/public"
  command = "npm install --legacy-peer-deps && npm install @rollup/rollup-linux-x64-gnu --save-dev && npx vite build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200